baseURL: "https://luispou.github.io/" 
title: Luis-Lara-Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Books
          url: books/
          weight: 5 
        - name: Courses
          url: courses/
          weight: 3
        - name: Data
          url: data/
          weight: 4 
        - name: Blog
          url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)
          weight: 6

params:
    description: "This website hosts Moritz-Maria von Igelfeld's research papers, books, course materials, data, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luis Lara
          subtitle: "I am a second-year Mechanical/Aerospace Engineering student with a minor in Electrical Engineering and Computer Sciences (EECS) at UC Berkeley. I am interested in autonomy, robotics, mechanical design, and aviation, and I am eager to gain industry experience to learn more! I enjoy working on hands-on engineering projects that integrate mechanical, electrical, and software systems to solve real-world problems."
          imageUrl: images/esb-luis.png
          imageWidth: 170
          imageHeight: 170
          buttons:
            - name: Resume
              url: cv.pdf
            - name: Data
              url: data/
            - name: Books
              url: books/
            - name: Courses
              url: courses/
            - name: Tags
              url: tags/
            - name: Archive
              url: archive/
            - name: Blog
              url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: Email
          url: mailto:user@gmail.com
        - name: GitHub
          url: https://github.com/user
        - name: LinkedIn
          url: https://www.linkedin.com/in/luis-lara-375a852bb/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Moritz-Maria von Igelfeld
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2