baseURL: "https://luispou.github.io/" 
title: Luis-Lara-Portfolio
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Portfolio
          url: books/
          weight: 5
        - name: Resume
          url: cv.pdf
          weight: 3
        - name: About Me
          url: data/
          weight: 4
        - name: LinkedIn
          url: https://www.linkedin.com/in/luis-lara-375a852bb/
          weight: 6

params:
    description: "This website hosts Luis Lara's portfolio, resume, and contact information."
    author: Luis Lara
    # googleAnalyticsID: G-XXXXX
    DateFormat: January 2006
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: [books, courses, data]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Luis Lara
          subtitle: "I am a second-year student at UC Berkeley studying Mechanical/Aerospace Engineering with a minor in Electrical Engineering and Computer Sciences (EECS). I am interested in autonomy, robotics, mechanical design, and aviation, and I am eager to gain industry experience to learn more! I enjoy working on hands-on engineering projects that integrate mechanical, electrical, and software systems to solve real-world problems."
          imageUrl: images/esb-luis.png
          imageWidth: 170
          imageHeight: 170
          buttons:
            - name: Resume
              url: cv.pdf
            - name: About Me
              url: data/
            - name: Portfolio
              url: books/
            - name: Project 1
              url: courses/
            - name: Project 2
              url: tags/
            - name: Project 3
              url: archive/
            - name: LinkedIn
              url: https://www.linkedin.com/in/luis-lara-375a852bb/

    socialIcons:
        - name: Email
          url: https://mail.google.com/mail/?view=cm&fs=1&to=luiflara0330@gmail.com
        - name: GitHub
          url: https://github.com/LuisPou
        - name: LinkedIn
          url: https://www.linkedin.com/in/luis-lara-375a852bb/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: Luis Lara
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2